### ISSUE TITLE
Unity - The type or namespace 'Cloud' does not exist in the namespace 'IBM' (are u missing an assembly reference?)

### ISSUE THREAD

**Issue by KingArmstring** [watson-developer-cloud/unity-sdk#597]
I just downloaded the sdk and placed it is the assets folder in Unity and immediately got this exception.

**Comment by mamoonraja** [comment]
Hi @KingArmstring! thanks for opening the issue. Can you please confirm whether you added the core package to the asset folder or not, see https://github.com/watson-developer-cloud/unity-sdk#installing-the-sdk-source-into-your-unity-project.

**Comment by bmoodyP3** [comment]
I am also having this issue.

**Comment by bmoodyP3** [comment]
I am using Unity version 2019.2.0f1 with Magic Leap. I am using unity-sdk-4.0.0 and unity-sdk-core-1.0.0. I also get the following errors:

![image](https://user-images.githubusercontent.com/52935156/66234972-db9bf680-e6a3-11e9-8d2e-8dca5d518d95.png)

**Comment by mamoonraja** [comment]
Do you have both `unity-sdk-core-1.0.0` in assets directory? I am using the same versions and not seeing an error right now.

**Comment by bmoodyP3** [comment]
Yes, both are in the top level.

**Comment by mamoonraja** [comment]
I just downloaded the [unity-sdk](https://github.com/watson-developer-cloud/unity-sdk/archive/v4.0.0.zip) and the [unity-sdk-core](Source code
(zip)) and built a new project in `Unity 2019.2.0f1` in Mac OS and I am not seeing the errors. However, I see errors when core is not correctly added. Try clearing the console after adding the core to the `Assets` directory. If the issue still persists please provide the following info:

- OS version (my guess is you are using Windows).
- A screenshot of project structure.

**Comment by mamoonraja** [comment]
Meanwhile, I am trying to build the project in Windows machine.

**Comment by bmoodyP3** [comment]
I made a new Unity project and now I have the following error:
![image](https://user-images.githubusercontent.com/52935156/66237874-0178c980-e6ab-11e9-81ae-f18903d10155.png)

**Comment by bmoodyP3** [comment]
This is my set up:
![image](https://user-images.githubusercontent.com/52935156/66237895-0d648b80-e6ab-11e9-9934-888f8a54c985.png)

**Comment by bmoodyP3** [comment]
I have some preview packages in use. Might that be the issue?

**Comment by bmoodyP3** [comment]
Here is my OS version: 
![image](https://user-images.githubusercontent.com/52935156/66239136-f3787800-e6ad-11e9-8717-afe946034195.png)

**Comment by mamoonraja** [comment]
That's good news because you can get rid of that error by following [instructions](https://github.com/watson-developer-cloud/unity-sdk#configuring-unity)

**Comment by bmoodyP3** [comment]
I tried again with my original project after updating my Windows and I continue to get the above error.

**Comment by bmoodyP3** [comment]
This is my project structure: 

![image](https://user-images.githubusercontent.com/52935156/66240484-9ed6fc00-e6b1-11e9-94f9-ea0429753e08.png)

**Comment by mamoonraja** [comment]
Looking closely at error message and directory structute it looks like you have `dll` file for WebSocket plugin saved in `Plugins/Websocket/*` and there is a dll file with the same name in `unity-sdk-core-1.0.0/Pulgins/*` too, you can rename either one and issue should resolve.

**Comment by bmoodyP3** [comment]
Hi @mamoonraja , thank you for your help. I did as you suggested and can now access Watson when I run the Magic Leap in the editor. However, when I try to build for the Magic Leap, I get the following errors:

**Comment by bmoodyP3** [comment]
![image](https://user-images.githubusercontent.com/52935156/66429185-68102700-e9cc-11e9-8580-bbb894e73530.png)

**Comment by bmoodyP3** [comment]
I was able to solve this by clicking, "include Lumin platform" on the Newsoft DLL in the following directory:

![image](https://user-images.githubusercontent.com/52935156/66439660-39527a80-e9e5-11e9-8e66-95779574779b.png)

**Comment by germanattanasio** [comment]
@bmoodyP3 feel free to open a PR if you think the installation instructions should be updated

**Comment by mamoonraja** [comment]
Since the issue is related to the Lumin platform and is resolved, I am closing this one.

**Comment by pluto93** [comment]
I am having the same issue. Tried all the solutions provided but I'm still facing this issue. I am using unity 2021.3.1f1, unity sdk 6.0.0 and unity sdk core 1.2.4
<img width="1266" alt="Screenshot 2024-01-31 at 12 10 17 pm" src="https://github.com/watson-developer-cloud/unity-sdk/assets/95747643/fe68f5ff-8fdf-4fd1-b3f2-d60031b58a0d">
